#!/bin/bash
# Quick seed script - paste this entire content into VM terminal

export PGPASSWORD='ENY0j6eAnRNBUjupSduEeMTL3VGnjsvFrifnhBeXIYE='

echo "🚀 Seeding 66 comprehensive questions..."

psql -h 34.134.76.171 -U financial_rise -d financial_rise_production << 'EOSQL'

-- Delete old questions
DELETE FROM questions;

-- Metadata (4 questions)
INSERT INTO questions (question_key, question_text, question_type, options, required, display_order, created_at, updated_at) VALUES
  ('META-001', 'What industry is your business in?', 'single_choice', '{"options": [{"value": "retail", "label": "Retail"}, {"value": "services", "label": "Professional Services"}, {"value": "manufacturing", "label": "Manufacturing"}, {"value": "technology", "label": "Technology/Software"}, {"value": "healthcare", "label": "Healthcare"}, {"value": "hospitality", "label": "Hospitality/Food Service"}, {"value": "construction", "label": "Construction/Trades"}, {"value": "other", "label": "Other"}]}', true, 1, NOW(), NOW()),
  ('META-002', 'How long has your business been operating?', 'single_choice', '{"options": [{"value": "under_1_year", "label": "Less than 1 year"}, {"value": "1_3_years", "label": "1-3 years"}, {"value": "3_5_years", "label": "3-5 years"}, {"value": "5_10_years", "label": "5-10 years"}, {"value": "over_10_years", "label": "More than 10 years"}]}', true, 2, NOW(), NOW()),
  ('META-003', 'What is your approximate annual revenue?', 'single_choice', '{"options": [{"value": "under_100k", "label": "Under $100,000"}, {"value": "100k_250k", "label": "$100,000 - $250,000"}, {"value": "250k_500k", "label": "$250,000 - $500,000"}, {"value": "500k_1m", "label": "$500,000 - $1 million"}, {"value": "1m_5m", "label": "$1 million - $5 million"}, {"value": "over_5m", "label": "Over $5 million"}]}', true, 3, NOW(), NOW()),
  ('META-004', 'How many employees do you have?', 'single_choice', '{"options": [{"value": "just_me", "label": "Just me (sole proprietor)"}, {"value": "1_5", "label": "1-5 employees"}, {"value": "6_10", "label": "6-10 employees"}, {"value": "11_25", "label": "11-25 employees"}, {"value": "26_50", "label": "26-50 employees"}, {"value": "over_50", "label": "More than 50 employees"}]}', true, 4, NOW(), NOW());

-- Stabilize (12 questions)
INSERT INTO questions (question_key, question_text, question_type, options, required, display_order, created_at, updated_at) VALUES
  ('STAB-001', 'How often do you review your financial statements (Profit & Loss, Balance Sheet)?', 'single_choice', '{"options": [{"value": "weekly", "label": "Weekly"}, {"value": "monthly", "label": "Monthly"}, {"value": "quarterly", "label": "Quarterly"}, {"value": "annually", "label": "Annually or less"}, {"value": "never", "label": "I don''t review them"}]}', true, 10, NOW(), NOW()),
  ('STAB-002', 'What is the current status of your bookkeeping?', 'single_choice', '{"options": [{"value": "current_professional", "label": "Current and managed by a professional"}, {"value": "current_self", "label": "Current and I do it myself"}, {"value": "behind_1_3_months", "label": "1-3 months behind"}, {"value": "behind_3_6_months", "label": "3-6 months behind"}, {"value": "behind_over_6_months", "label": "More than 6 months behind"}]}', true, 11, NOW(), NOW()),
  ('STAB-003', 'How often do you reconcile your bank accounts?', 'single_choice', '{"options": [{"value": "monthly", "label": "Monthly"}, {"value": "quarterly", "label": "Quarterly"}, {"value": "annually", "label": "Annually"}, {"value": "never", "label": "I don''t reconcile"}]}', true, 12, NOW(), NOW()),
  ('STAB-004', 'Are your business tax returns filed on time and current?', 'single_choice', '{"options": [{"value": "yes_all_current", "label": "Yes, all returns are current"}, {"value": "mostly_current", "label": "Mostly current, minor delays"}, {"value": "some_late", "label": "Some returns are late or on extension"}, {"value": "significantly_behind", "label": "Significantly behind on filings"}]}', true, 13, NOW(), NOW()),
  ('STAB-005', 'Do you track accounts receivable (money owed to you)?', 'single_choice', '{"options": [{"value": "yes_system", "label": "Yes, using an automated system"}, {"value": "yes_manual", "label": "Yes, manually tracking"}, {"value": "sometimes", "label": "Sometimes, not consistently"}, {"value": "no", "label": "No, I don''t track AR"}, {"value": "not_applicable", "label": "Not applicable (cash business)"}]}', true, 14, NOW(), NOW()),
  ('STAB-006', 'Do you track accounts payable (money you owe)?', 'single_choice', '{"options": [{"value": "yes_system", "label": "Yes, using an automated system"}, {"value": "yes_manual", "label": "Yes, manually tracking"}, {"value": "sometimes", "label": "Sometimes, not consistently"}, {"value": "no", "label": "No, I don''t track AP"}]}', true, 15, NOW(), NOW()),
  ('STAB-007', 'Do you have a clear understanding of all your business debts and payment schedules?', 'single_choice', '{"options": [{"value": "yes_documented", "label": "Yes, fully documented and managed"}, {"value": "yes_informal", "label": "Yes, but not formally documented"}, {"value": "partial", "label": "Partial understanding"}, {"value": "no", "label": "No clear understanding"}, {"value": "no_debt", "label": "We have no business debt"}]}', true, 16, NOW(), NOW()),
  ('STAB-008', 'Are your personal and business finances completely separated?', 'single_choice', '{"options": [{"value": "yes_fully", "label": "Yes, completely separated"}, {"value": "mostly", "label": "Mostly separated, occasional mixing"}, {"value": "partially", "label": "Partially separated"}, {"value": "no", "label": "No, they are mixed together"}]}', true, 17, NOW(), NOW()),
  ('STAB-009', 'If you have employees, how do you manage payroll?', 'single_choice', '{"options": [{"value": "payroll_service", "label": "Professional payroll service"}, {"value": "accounting_software", "label": "Accounting software (QuickBooks, etc.)"}, {"value": "manual", "label": "Manual calculations"}, {"value": "no_employees", "label": "No employees"}]}', true, 18, NOW(), NOW()),
  ('STAB-010', 'Do you collect and remit sales tax (if applicable)?', 'single_choice', '{"options": [{"value": "yes_automated", "label": "Yes, using automated system"}, {"value": "yes_manual", "label": "Yes, tracking manually"}, {"value": "inconsistent", "label": "Inconsistently"}, {"value": "no", "label": "No, but I should be"}, {"value": "not_applicable", "label": "Not applicable to my business"}]}', true, 19, NOW(), NOW()),
  ('STAB-011', 'How organized are your financial records and receipts?', 'rating', '{"min": 1, "max": 5, "min_label": "Completely disorganized", "max_label": "Highly organized"}', true, 20, NOW(), NOW()),
  ('STAB-012', 'Does your business have an emergency fund or cash reserves?', 'single_choice', '{"options": [{"value": "3_months_plus", "label": "Yes, 3+ months of expenses"}, {"value": "1_3_months", "label": "Yes, 1-3 months of expenses"}, {"value": "under_1_month", "label": "Less than 1 month"}, {"value": "no", "label": "No emergency fund"}]}', true, 21, NOW(), NOW());

-- Organize (10 questions)
INSERT INTO questions (question_key, question_text, question_type, options, required, display_order, created_at, updated_at) VALUES
  ('ORG-001', 'What is your business entity type?', 'single_choice', '{"options": [{"value": "sole_proprietor", "label": "Sole Proprietor"}, {"value": "llc", "label": "LLC (Single or Multi-Member)"}, {"value": "s_corp", "label": "S-Corporation"}, {"value": "c_corp", "label": "C-Corporation"}, {"value": "partnership", "label": "Partnership"}, {"value": "not_sure", "label": "Not sure"}]}', true, 30, NOW(), NOW()),
  ('ORG-002', 'As an S-Corp owner, are you on payroll with a reasonable salary?', 'single_choice', '{"options": [{"value": "yes", "label": "Yes, I take a regular salary"}, {"value": "no", "label": "No, I''m not on payroll"}, {"value": "distributions_only", "label": "I only take distributions"}]}', false, 31, NOW(), NOW()),
  ('ORG-003', 'Do you have a well-organized Chart of Accounts?', 'single_choice', '{"options": [{"value": "yes_customized", "label": "Yes, customized for my business"}, {"value": "yes_default", "label": "Yes, using default/template"}, {"value": "basic", "label": "Basic setup, not optimized"}, {"value": "no", "label": "No formal Chart of Accounts"}]}', true, 32, NOW(), NOW()),
  ('ORG-004', 'What accounting software do you use?', 'single_choice', '{"options": [{"value": "quickbooks", "label": "QuickBooks (Desktop or Online)"}, {"value": "xero", "label": "Xero"}, {"value": "freshbooks", "label": "FreshBooks"}, {"value": "wave", "label": "Wave"}, {"value": "spreadsheet", "label": "Excel/Google Sheets"}, {"value": "other", "label": "Other software"}, {"value": "none", "label": "No software, manual tracking"}]}', true, 33, NOW(), NOW()),
  ('ORG-005', 'Are your business systems integrated (e.g., POS, inventory, accounting)?', 'single_choice', '{"options": [{"value": "fully_integrated", "label": "Fully integrated and automated"}, {"value": "partially_integrated", "label": "Partially integrated"}, {"value": "manual_entry", "label": "Manual data entry between systems"}, {"value": "no_integration", "label": "No integration"}, {"value": "not_applicable", "label": "Not applicable (simple business)"}]}', true, 34, NOW(), NOW()),
  ('ORG-006', 'If you have inventory, how do you track it?', 'single_choice', '{"options": [{"value": "system_integrated", "label": "Inventory management system (integrated)"}, {"value": "system_separate", "label": "Inventory system (not integrated)"}, {"value": "spreadsheet", "label": "Spreadsheet tracking"}, {"value": "no_tracking", "label": "No formal tracking"}, {"value": "no_inventory", "label": "No physical inventory"}]}', true, 35, NOW(), NOW()),
  ('ORG-007', 'How do you process customer payments?', 'multiple_choice', '{"options": [{"value": "credit_cards", "label": "Credit/debit cards"}, {"value": "ach_bank_transfer", "label": "ACH/bank transfers"}, {"value": "checks", "label": "Checks"}, {"value": "cash", "label": "Cash"}, {"value": "digital_wallet", "label": "Digital wallets (PayPal, Venmo, etc.)"}, {"value": "invoicing_software", "label": "Invoicing software"}]}', true, 36, NOW(), NOW()),
  ('ORG-008', 'How do you store important financial documents?', 'single_choice', '{"options": [{"value": "cloud_organized", "label": "Cloud storage, well organized"}, {"value": "cloud_messy", "label": "Cloud storage, somewhat disorganized"}, {"value": "physical_organized", "label": "Physical files, well organized"}, {"value": "physical_messy", "label": "Physical files, disorganized"}, {"value": "mixed", "label": "Mix of physical and digital, no clear system"}]}', true, 37, NOW(), NOW()),
  ('ORG-009', 'Do you have a system for managing vendor relationships and contracts?', 'single_choice', '{"options": [{"value": "yes_formal", "label": "Yes, formal vendor management system"}, {"value": "spreadsheet", "label": "Yes, tracking in spreadsheet"}, {"value": "informal", "label": "Informal tracking"}, {"value": "no", "label": "No vendor tracking"}]}', true, 38, NOW(), NOW()),
  ('ORG-010', 'How clear are your financial workflows and processes?', 'rating', '{"min": 1, "max": 5, "min_label": "No clear processes", "max_label": "Fully documented processes"}', true, 39, NOW(), NOW());

-- Build (10 questions)
INSERT INTO questions (question_key, question_text, question_type, options, required, display_order, created_at, updated_at) VALUES
  ('BUILD-001', 'Do you have documented Standard Operating Procedures (SOPs) for financial tasks?', 'single_choice', '{"options": [{"value": "comprehensive", "label": "Yes, comprehensive SOPs for all major tasks"}, {"value": "some", "label": "Yes, for some tasks"}, {"value": "informal", "label": "Informal/undocumented processes"}, {"value": "no", "label": "No SOPs"}]}', true, 50, NOW(), NOW()),
  ('BUILD-002', 'Do you operate with a formal budget?', 'single_choice', '{"options": [{"value": "yes_detailed", "label": "Yes, detailed annual budget with monthly tracking"}, {"value": "yes_basic", "label": "Yes, basic budget"}, {"value": "informal", "label": "Informal spending guidelines"}, {"value": "no", "label": "No budget"}]}', true, 51, NOW(), NOW()),
  ('BUILD-003', 'How often do you review actual vs. budgeted performance?', 'single_choice', '{"options": [{"value": "monthly", "label": "Monthly"}, {"value": "quarterly", "label": "Quarterly"}, {"value": "annually", "label": "Annually"}, {"value": "never", "label": "Never/No budget to compare"}]}', true, 52, NOW(), NOW()),
  ('BUILD-004', 'Do you have formal approval processes for major expenses?', 'single_choice', '{"options": [{"value": "yes_documented", "label": "Yes, documented approval workflows"}, {"value": "yes_informal", "label": "Yes, informal approval required"}, {"value": "threshold_only", "label": "Only for expenses above certain threshold"}, {"value": "no", "label": "No formal approval process"}]}', true, 53, NOW(), NOW()),
  ('BUILD-005', 'How often do you generate financial reports for decision-making?', 'single_choice', '{"options": [{"value": "weekly", "label": "Weekly"}, {"value": "monthly", "label": "Monthly"}, {"value": "quarterly", "label": "Quarterly"}, {"value": "annually", "label": "Annually or less"}, {"value": "never", "label": "Rarely/Never"}]}', true, 54, NOW(), NOW()),
  ('BUILD-006', 'Have you provided financial training to relevant team members?', 'single_choice', '{"options": [{"value": "ongoing", "label": "Yes, ongoing training program"}, {"value": "initial", "label": "Yes, initial training only"}, {"value": "informal", "label": "Informal on-the-job training"}, {"value": "no", "label": "No formal training"}, {"value": "no_team", "label": "No team members handling finances"}]}', true, 55, NOW(), NOW()),
  ('BUILD-007', 'Do you have internal controls to prevent fraud or errors?', 'single_choice', '{"options": [{"value": "comprehensive", "label": "Yes, comprehensive controls in place"}, {"value": "basic", "label": "Yes, basic controls"}, {"value": "minimal", "label": "Minimal controls"}, {"value": "no", "label": "No formal controls"}]}', true, 56, NOW(), NOW()),
  ('BUILD-008', 'How consistent is your expense categorization?', 'rating', '{"min": 1, "max": 5, "min_label": "Inconsistent/random", "max_label": "Highly consistent"}', true, 57, NOW(), NOW()),
  ('BUILD-009', 'Do you use a financial dashboard to monitor key metrics?', 'single_choice', '{"options": [{"value": "yes_automated", "label": "Yes, automated real-time dashboard"}, {"value": "yes_manual", "label": "Yes, manually updated dashboard"}, {"value": "spreadsheet", "label": "Track metrics in spreadsheet"}, {"value": "no", "label": "No dashboard or metrics tracking"}]}', true, 58, NOW(), NOW()),
  ('BUILD-010', 'Have you automated any financial processes?', 'multiple_choice', '{"options": [{"value": "bill_pay", "label": "Bill payment"}, {"value": "invoicing", "label": "Invoicing"}, {"value": "expense_tracking", "label": "Expense tracking"}, {"value": "payroll", "label": "Payroll"}, {"value": "reconciliation", "label": "Bank reconciliation"}, {"value": "reporting", "label": "Financial reporting"}, {"value": "none", "label": "None - all manual processes"}]}', true, 59, NOW(), NOW());

-- Grow (10 questions)
INSERT INTO questions (question_key, question_text, question_type, options, required, display_order, created_at, updated_at) VALUES
  ('GROW-001', 'Do you regularly forecast your cash flow?', 'single_choice', '{"options": [{"value": "yes_rolling", "label": "Yes, rolling 13-week or longer forecast"}, {"value": "yes_monthly", "label": "Yes, monthly forecasting"}, {"value": "quarterly", "label": "Quarterly forecasting"}, {"value": "no", "label": "No regular cash flow forecasting"}]}', true, 70, NOW(), NOW()),
  ('GROW-002', 'How do you approach revenue projections?', 'single_choice', '{"options": [{"value": "data_driven", "label": "Data-driven models with multiple scenarios"}, {"value": "historical", "label": "Based on historical trends"}, {"value": "gut_feeling", "label": "Educated guesses"}, {"value": "no_projections", "label": "Don''t create revenue projections"}]}', true, 71, NOW(), NOW()),
  ('GROW-003', 'Do you create different scenarios for business planning (best case, worst case, etc.)?', 'single_choice', '{"options": [{"value": "yes_detailed", "label": "Yes, detailed scenario planning"}, {"value": "yes_basic", "label": "Yes, basic scenarios"}, {"value": "occasionally", "label": "Occasionally"}, {"value": "no", "label": "No scenario planning"}]}', true, 72, NOW(), NOW()),
  ('GROW-004', 'Do you have a plan for major capital expenditures?', 'single_choice', '{"options": [{"value": "yes_multi_year", "label": "Yes, multi-year capital plan"}, {"value": "yes_annual", "label": "Yes, annual capital budget"}, {"value": "ad_hoc", "label": "Ad hoc decisions as needs arise"}, {"value": "no", "label": "No capital planning"}]}', true, 73, NOW(), NOW()),
  ('GROW-005', 'Do you have a documented growth strategy with financial targets?', 'single_choice', '{"options": [{"value": "yes_detailed", "label": "Yes, detailed strategy with milestones"}, {"value": "yes_basic", "label": "Yes, basic goals outlined"}, {"value": "informal", "label": "Informal growth plans"}, {"value": "no", "label": "No formal growth strategy"}]}', true, 74, NOW(), NOW()),
  ('GROW-006', 'Do you analyze profitability by product/service line?', 'single_choice', '{"options": [{"value": "yes_regular", "label": "Yes, regular detailed analysis"}, {"value": "yes_occasional", "label": "Yes, occasionally"}, {"value": "high_level", "label": "Only high-level profit analysis"}, {"value": "no", "label": "No profitability analysis by segment"}]}', true, 75, NOW(), NOW()),
  ('GROW-007', 'Do you track customer acquisition cost (CAC) and lifetime value (LTV)?', 'single_choice', '{"options": [{"value": "yes_both", "label": "Yes, track both CAC and LTV"}, {"value": "yes_one", "label": "Yes, track one of them"}, {"value": "informal", "label": "Have rough estimates"}, {"value": "no", "label": "Don''t track these metrics"}]}', true, 76, NOW(), NOW()),
  ('GROW-008', 'Do you have a strategy for funding growth (loans, investors, bootstrapping)?', 'single_choice', '{"options": [{"value": "yes_documented", "label": "Yes, documented funding strategy"}, {"value": "yes_informal", "label": "Yes, informal plan"}, {"value": "exploring", "label": "Currently exploring options"}, {"value": "no", "label": "No funding strategy"}]}', true, 77, NOW(), NOW()),
  ('GROW-009', 'Do you use financial models to test business decisions?', 'single_choice', '{"options": [{"value": "yes_sophisticated", "label": "Yes, sophisticated financial models"}, {"value": "yes_basic", "label": "Yes, basic financial models"}, {"value": "spreadsheet", "label": "Simple spreadsheet calculations"}, {"value": "no", "label": "No financial modeling"}]}', true, 78, NOW(), NOW()),
  ('GROW-010', 'Do you work with a financial advisor or CFO for strategic planning?', 'single_choice', '{"options": [{"value": "fractional_cfo", "label": "Yes, fractional CFO or advisor"}, {"value": "consultant", "label": "Yes, occasional consultant"}, {"value": "accountant", "label": "My accountant provides some guidance"}, {"value": "no", "label": "No external financial guidance"}]}', true, 79, NOW(), NOW());

-- Systemic (8 questions)
INSERT INTO questions (question_key, question_text, question_type, options, required, display_order, created_at, updated_at) VALUES
  ('SYS-001', 'How comfortable are you reading and interpreting financial statements?', 'rating', '{"min": 1, "max": 5, "min_label": "Very uncomfortable", "max_label": "Very comfortable"}', true, 90, NOW(), NOW()),
  ('SYS-002', 'How often do you use financial data to make business decisions?', 'single_choice', '{"options": [{"value": "always", "label": "Always - data drives all major decisions"}, {"value": "often", "label": "Often - for most important decisions"}, {"value": "sometimes", "label": "Sometimes - when I remember to check"}, {"value": "rarely", "label": "Rarely - mostly rely on intuition"}, {"value": "never", "label": "Never - don''t use financial data"}]}', true, 91, NOW(), NOW()),
  ('SYS-003', 'Do you regularly monitor Key Performance Indicators (KPIs)?', 'single_choice', '{"options": [{"value": "yes_multiple", "label": "Yes, track multiple KPIs weekly"}, {"value": "yes_monthly", "label": "Yes, track KPIs monthly"}, {"value": "yes_occasional", "label": "Yes, check occasionally"}, {"value": "no", "label": "No regular KPI tracking"}]}', true, 92, NOW(), NOW()),
  ('SYS-004', 'Do you understand what metrics are most important for your business?', 'single_choice', '{"options": [{"value": "yes_clear", "label": "Yes, very clear on key metrics"}, {"value": "yes_mostly", "label": "Yes, mostly understand"}, {"value": "somewhat", "label": "Somewhat understand"}, {"value": "no", "label": "Not sure what metrics matter"}]}', true, 93, NOW(), NOW()),
  ('SYS-005', 'Do you teach financial literacy to your team members?', 'single_choice', '{"options": [{"value": "yes_program", "label": "Yes, formal training program"}, {"value": "yes_informal", "label": "Yes, informal teaching"}, {"value": "occasionally", "label": "Occasionally share insights"}, {"value": "no", "label": "No financial literacy training for team"}, {"value": "no_team", "label": "No team members"}]}', true, 94, NOW(), NOW()),
  ('SYS-006', 'How do you stay educated on financial management?', 'multiple_choice', '{"options": [{"value": "courses", "label": "Take courses/workshops"}, {"value": "books", "label": "Read books/articles"}, {"value": "advisor", "label": "Work with advisor/mentor"}, {"value": "peer_groups", "label": "Peer groups/masterminds"}, {"value": "podcasts", "label": "Podcasts/webinars"}, {"value": "conferences", "label": "Attend conferences"}, {"value": "none", "label": "Don''t actively seek financial education"}]}', true, 95, NOW(), NOW()),
  ('SYS-007', 'Do you set and track financial goals?', 'single_choice', '{"options": [{"value": "yes_detailed", "label": "Yes, detailed goals with regular tracking"}, {"value": "yes_basic", "label": "Yes, basic goals"}, {"value": "informal", "label": "Informal goals in mind"}, {"value": "no", "label": "No specific financial goals"}]}', true, 96, NOW(), NOW()),
  ('SYS-008', 'How would you rate your overall financial awareness of your business?', 'rating', '{"min": 1, "max": 5, "min_label": "Very low awareness", "max_label": "Excellent awareness"}', true, 97, NOW(), NOW());

-- DISC (12 questions)
INSERT INTO questions (question_key, question_text, question_type, options, required, display_order, created_at, updated_at) VALUES
  ('DISC-001', 'When communicating about business challenges, I prefer:', 'single_choice', '{"options": [{"value": "direct_brief", "label": "Direct and brief - get to the point quickly"}, {"value": "collaborative", "label": "Collaborative discussion with the team"}, {"value": "thoughtful_steady", "label": "Thoughtful, step-by-step explanation"}, {"value": "detailed_data", "label": "Detailed with supporting data and analysis"}]}', true, 100, NOW(), NOW()),
  ('DISC-002', 'When making important business decisions, I tend to:', 'single_choice', '{"options": [{"value": "decide_quickly", "label": "Decide quickly and move forward"}, {"value": "discuss_options", "label": "Discuss options with others first"}, {"value": "consider_impact", "label": "Carefully consider impact on everyone"}, {"value": "analyze_thoroughly", "label": "Analyze all data thoroughly before deciding"}]}', true, 101, NOW(), NOW()),
  ('DISC-003', 'My preferred work pace is:', 'single_choice', '{"options": [{"value": "fast_results", "label": "Fast-paced, focused on results"}, {"value": "energetic_varied", "label": "Energetic with variety"}, {"value": "steady_consistent", "label": "Steady and consistent"}, {"value": "methodical_precise", "label": "Methodical and precise"}]}', true, 102, NOW(), NOW()),
  ('DISC-004', 'When it comes to business risks, I:', 'single_choice', '{"options": [{"value": "embrace_challenge", "label": "Embrace challenges and take calculated risks"}, {"value": "optimistic", "label": "Stay optimistic about new opportunities"}, {"value": "cautious_secure", "label": "Prefer security and proven approaches"}, {"value": "analyze_risks", "label": "Carefully analyze all potential risks"}]}', true, 103, NOW(), NOW()),
  ('DISC-005', 'In team settings, I am most likely to:', 'single_choice', '{"options": [{"value": "take_charge", "label": "Take charge and drive results"}, {"value": "energize_team", "label": "Energize the team and build enthusiasm"}, {"value": "support_harmony", "label": "Support others and maintain harmony"}, {"value": "ensure_quality", "label": "Ensure quality and accuracy"}]}', true, 104, NOW(), NOW()),
  ('DISC-006', 'When facing a business problem, I:', 'single_choice', '{"options": [{"value": "solve_quickly", "label": "Want to solve it quickly and efficiently"}, {"value": "brainstorm", "label": "Like to brainstorm creative solutions with others"}, {"value": "consider_people", "label": "Consider how it affects people involved"}, {"value": "research_analyze", "label": "Research and analyze all possible solutions"}]}', true, 105, NOW(), NOW()),
  ('DISC-007', 'What matters most to me in business is:', 'single_choice', '{"options": [{"value": "achievement", "label": "Achievement and results"}, {"value": "relationships", "label": "Relationships and collaboration"}, {"value": "stability", "label": "Stability and consistency"}, {"value": "accuracy", "label": "Accuracy and quality"}]}', true, 106, NOW(), NOW()),
  ('DISC-008', 'When reviewing financial information, I prefer:', 'single_choice', '{"options": [{"value": "summary", "label": "Summary of key numbers and action items"}, {"value": "visual_overview", "label": "Visual overview with highlights"}, {"value": "clear_explanation", "label": "Clear step-by-step explanation"}, {"value": "comprehensive_detail", "label": "Comprehensive detail and documentation"}]}', true, 107, NOW(), NOW()),
  ('DISC-009', 'When business changes are needed, I:', 'single_choice', '{"options": [{"value": "drive_change", "label": "Drive change decisively"}, {"value": "inspire_enthusiasm", "label": "Inspire enthusiasm for the change"}, {"value": "need_time", "label": "Need time to adapt and prefer gradual shifts"}, {"value": "evaluate_thoroughly", "label": "Want to evaluate the change thoroughly first"}]}', true, 108, NOW(), NOW()),
  ('DISC-010', 'I prefer feedback that is:', 'single_choice', '{"options": [{"value": "direct_concise", "label": "Direct and concise"}, {"value": "positive_encouraging", "label": "Positive and encouraging"}, {"value": "supportive_patient", "label": "Supportive and patient"}, {"value": "specific_detailed", "label": "Specific and detailed"}]}', true, 109, NOW(), NOW()),
  ('DISC-011', 'My approach to planning is:', 'single_choice', '{"options": [{"value": "quick_action", "label": "Quick planning, focus on action"}, {"value": "big_picture", "label": "Big picture vision with flexibility"}, {"value": "careful_thorough", "label": "Careful and thorough"}, {"value": "detailed_systematic", "label": "Detailed and systematic"}]}', true, 110, NOW(), NOW()),
  ('DISC-012', 'Success in business means:', 'single_choice', '{"options": [{"value": "winning_achieving", "label": "Winning and achieving ambitious goals"}, {"value": "recognition_impact", "label": "Recognition and making a positive impact"}, {"value": "security_loyalty", "label": "Security and loyal relationships"}, {"value": "excellence_mastery", "label": "Excellence and mastery"}]}', true, 111, NOW(), NOW());

-- Show counts
SELECT
  COUNT(*) FILTER (WHERE question_key LIKE 'META-%') as metadata,
  COUNT(*) FILTER (WHERE question_key LIKE 'STAB-%') as stabilize,
  COUNT(*) FILTER (WHERE question_key LIKE 'ORG-%') as organize,
  COUNT(*) FILTER (WHERE question_key LIKE 'BUILD-%') as build,
  COUNT(*) FILTER (WHERE question_key LIKE 'GROW-%') as grow,
  COUNT(*) FILTER (WHERE question_key LIKE 'SYS-%') as systemic,
  COUNT(*) FILTER (WHERE question_key LIKE 'DISC-%') as disc,
  COUNT(*) as total
FROM questions;

EOSQL

echo ""
echo "✅ Deployment complete!"
