/**
 * ChecklistItem Model
 *
 * Represents an action item in a checklist associated with an assessment.
 * Items can be auto-generated from report recommendations or manually created.
 * Both consultants and clients can mark items as complete.
 *
 * @module models/ChecklistItem
 * @version 1.0
 * @date 2025-12-22
 */

import { Model, DataTypes, Sequelize, Optional } from 'sequelize';

/**
 * ChecklistItem attributes interface
 */
export interface ChecklistItemAttributes {
  id: string;
  assessment_id: string;

  // Item content
  title: string;
  description?: string;
  phase: 'Stabilize' | 'Organize' | 'Build' | 'Grow' | 'Systemic';
  priority: 0 | 1 | 2 | 3; // 0=none, 1=low, 2=medium, 3=high
  sort_order: number;

  // Completion tracking
  is_completed: boolean;
  completed_at?: Date;
  completed_by?: string;

  // Client notes
  client_notes?: string;
  client_notes_updated_at?: Date;

  // Auto-generation metadata
  auto_generated: boolean;
  source_recommendation_id?: string;

  // Audit fields
  created_at: Date;
  created_by: string;
  updated_at: Date;
  updated_by?: string;
  deleted_at?: Date;
}

/**
 * Optional attributes for creation (auto-generated fields)
 */
export interface ChecklistItemCreationAttributes
  extends Optional<
    ChecklistItemAttributes,
    'id' | 'description' | 'priority' | 'sort_order' | 'is_completed' |
    'completed_at' | 'completed_by' | 'client_notes' | 'client_notes_updated_at' |
    'auto_generated' | 'source_recommendation_id' | 'created_at' |
    'updated_at' | 'updated_by' | 'deleted_at'
  > {}

/**
 * ChecklistItem Model Class
 *
 * Supports:
 * - CRUD operations
 * - Soft deletes (paranoid mode)
 * - Auto-generated timestamps
 * - Validation constraints
 */
export class ChecklistItem extends Model<
  ChecklistItemAttributes,
  ChecklistItemCreationAttributes
> implements ChecklistItemAttributes {
  // Primary key
  public id!: string;
  public assessment_id!: string;

  // Item content
  public title!: string;
  public description?: string;
  public phase!: 'Stabilize' | 'Organize' | 'Build' | 'Grow' | 'Systemic';
  public priority!: 0 | 1 | 2 | 3;
  public sort_order!: number;

  // Completion tracking
  public is_completed!: boolean;
  public completed_at?: Date;
  public completed_by?: string;

  // Client notes
  public client_notes?: string;
  public client_notes_updated_at?: Date;

  // Auto-generation metadata
  public auto_generated!: boolean;
  public source_recommendation_id?: string;

  // Audit fields
  public created_at!: Date;
  public created_by!: string;
  public updated_at!: Date;
  public updated_by?: string;
  public deleted_at?: Date;

  /**
   * Helper method to check if item is in a specific phase
   */
  public isInPhase(phase: string): boolean {
    return this.phase === phase;
  }

  /**
   * Helper method to check if item was auto-generated
   */
  public isAutoGenerated(): boolean {
    return this.auto_generated === true;
  }

  /**
   * Helper method to check if item has client notes
   */
  public hasClientNotes(): boolean {
    return !!this.client_notes && this.client_notes.trim().length > 0;
  }
}

/**
 * Initialize the ChecklistItem model
 *
 * @param sequelize - Sequelize instance
 * @returns Initialized ChecklistItem model
 */
export function initChecklistItemModel(sequelize: Sequelize): typeof ChecklistItem {
  ChecklistItem.init(
    {
      id: {
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4,
        primaryKey: true,
        comment: 'Unique identifier for the checklist item'
      },
      assessment_id: {
        type: DataTypes.UUID,
        allowNull: false,
        references: {
          model: 'assessments',
          key: 'id'
        },
        onDelete: 'CASCADE',
        comment: 'Foreign key to assessments table'
      },
      title: {
        type: DataTypes.STRING(500),
        allowNull: false,
        validate: {
          notEmpty: {
            msg: 'Title cannot be empty'
          },
          len: {
            args: [1, 500],
            msg: 'Title must be between 1 and 500 characters'
          }
        },
        comment: 'Short title/summary of the action item'
      },
      description: {
        type: DataTypes.TEXT,
        allowNull: true,
        comment: 'Detailed description of the action item'
      },
      phase: {
        type: DataTypes.STRING(50),
        allowNull: false,
        validate: {
          isIn: {
            args: [['Stabilize', 'Organize', 'Build', 'Grow', 'Systemic']],
            msg: 'Phase must be one of: Stabilize, Organize, Build, Grow, Systemic'
          }
        },
        comment: 'Financial phase this item belongs to'
      },
      priority: {
        type: DataTypes.INTEGER,
        defaultValue: 0,
        allowNull: false,
        validate: {
          min: {
            args: [0],
            msg: 'Priority must be at least 0'
          },
          max: {
            args: [3],
            msg: 'Priority must be at most 3'
          }
        },
        comment: 'Priority level: 0=none, 1=low, 2=medium, 3=high'
      },
      sort_order: {
        type: DataTypes.INTEGER,
        allowNull: false,
        defaultValue: 0,
        comment: 'Order of item within the checklist'
      },
      is_completed: {
        type: DataTypes.BOOLEAN,
        defaultValue: false,
        allowNull: false,
        comment: 'Whether the item has been marked complete'
      },
      completed_at: {
        type: DataTypes.DATE,
        allowNull: true,
        comment: 'Timestamp when item was marked complete'
      },
      completed_by: {
        type: DataTypes.UUID,
        allowNull: true,
        references: {
          model: 'users',
          key: 'id'
        },
        comment: 'User ID who marked item complete (consultant or client)'
      },
      client_notes: {
        type: DataTypes.TEXT,
        allowNull: true,
        comment: 'Notes added by the client about this item'
      },
      client_notes_updated_at: {
        type: DataTypes.DATE,
        allowNull: true,
        comment: 'Timestamp when client notes were last updated'
      },
      auto_generated: {
        type: DataTypes.BOOLEAN,
        defaultValue: false,
        allowNull: false,
        comment: 'True if item was auto-generated from report'
      },
      source_recommendation_id: {
        type: DataTypes.STRING(100),
        allowNull: true,
        comment: 'Reference to recommendation in report that generated this item'
      },
      created_at: {
        type: DataTypes.DATE,
        defaultValue: DataTypes.NOW,
        allowNull: false,
        comment: 'Timestamp when item was created'
      },
      created_by: {
        type: DataTypes.UUID,
        allowNull: false,
        references: {
          model: 'users',
          key: 'id'
        },
        comment: 'User ID who created the item (usually consultant)'
      },
      updated_at: {
        type: DataTypes.DATE,
        defaultValue: DataTypes.NOW,
        allowNull: false,
        comment: 'Timestamp when item was last updated'
      },
      updated_by: {
        type: DataTypes.UUID,
        allowNull: true,
        references: {
          model: 'users',
          key: 'id'
        },
        comment: 'User ID who last updated the item'
      },
      deleted_at: {
        type: DataTypes.DATE,
        allowNull: true,
        comment: 'Soft delete timestamp - item is hidden but not removed'
      }
    },
    {
      sequelize,
      tableName: 'checklist_items',
      timestamps: true,
      paranoid: true, // Enable soft deletes
      underscored: true,
      createdAt: 'created_at',
      updatedAt: 'updated_at',
      deletedAt: 'deleted_at',
      indexes: [
        {
          name: 'idx_checklist_items_assessment_id',
          fields: ['assessment_id']
        },
        {
          name: 'idx_checklist_items_phase',
          fields: ['phase']
        },
        {
          name: 'idx_checklist_items_completed',
          fields: ['is_completed']
        },
        {
          name: 'idx_checklist_items_sort_order',
          fields: ['assessment_id', 'sort_order']
        },
        {
          name: 'idx_checklist_items_deleted_at',
          fields: ['deleted_at']
        }
      ]
    }
  );

  return ChecklistItem;
}

export default ChecklistItem;
